version: '3'

services:
  db:
    container_name: Mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p', 'root' ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "Teste"
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d
